const { createHoverRuntimeFeature } = require('../../features/hover/factory');
const { createPersistentHoverFeature } = require('../../features/persistent-hover');

function buildHoverFeatures(deps, support) {
    const {
        vscode,
        liveValidationOutputChannel = null
    } = deps;
    const { settingsRuntime, sharedRuntime } = deps.coreRuntime;
    const {
        HOVER_RELEVANT_CONFIG_KEYS,
        PERSISTENT_HOVER_RELEVANT_CONFIG_KEYS,
        affectsAnyConfiguration,
        refreshExtensionSettings,
        getHoverMode,
        getHoverContentMode,
        getIncludeValidationMode,
        getLiveValidationIssueMode,
        getIncludeFileExtensions,
        getGlobalIncludePaths,
        getProjectLocalIncludePaths,
        getProgrammaticIncludePaths,
        getPersistentHoverMode,
        isPersistentHoverEnabled,
        isHoverGoToDefinitionLinksEnabled
    } = settingsRuntime;
    const {
        t,
        isPawnDocument,
        isSameFilePath,
        getDocumentTextAndResolver,
        getPawnDocumentContext,
        getLookupTokenAtPosition,
        isLinePositionInsideCommentOrString,
        findHeaderFunctionByNameAtPosition,
        findFunctionDeclarationNameContext,
        findDefinitionContext,
        findFunctionCallNameContext,
        findCallContext,
        findMatchingParenOffset,
        collectInlineNamedCallContexts,
        findNestedParentCallNameContext,
        getWordAtPosition,
        findPreferredKnownCallContext,
        getPreferredFunctionHoverMatch,
        hasIncludeFunctionTwin,
        isKnownFunctionName,
        isNearbyCallContext,
        isMeaningfulCallCursorPosition,
        isMeaningfulCallPosition,
        findIndexedAccessContextAtPosition,
        buildIndexedAccessSelectionModel,
        resolveDefaultAccessSymbolName,
        findVariableDeclarationSpanInRange,
        shouldSuppressVariableDeclarationValidationInRange,
        isVariableDeclarationNameAtPosition,
        isOriginalDeclarationHover,
        buildCallArgLayout,
        collectCallArgumentIssues,
        expandObjectLikeDefineTupleCallArgs,
        createLazyCallContextOptions,
        collectIndexedAccessExpressionsFromLine,
        extractCallSiteArgs,
        splitTopLevel,
        splitTopLevelWithRanges,
        parseFuncArgs,
        parseDimsParts,
        parseDimSpec,
        parseIndexedAccessExpression,
        createHoverTypeAnalysisCache,
        explainIndexedAccessDimCompat,
        resolveIndexedAccessValidationChain,
        computeLineDepths,
        computeFunctionRangeMaps,
        getActiveCtrlChar,
        stripLineComment,
        isEscapedQuote,
        extractEnumSymbolName,
        getEnumDeclsForVariableDims,
        buildEnumMemberLine,
        getVariableInitializerUsageText,
        buildSig,
        measurePawnStringLiteral,
        normalizeLiveValidationIssueMode,
        areLiveValidationWarningsEnabled,
        isFunctionLikeDefineDecl,
        isFunctionLikeDecl,
        collectWordDeclMatches,
        getDeclMatchKey,
        finalizeDeclMatches,
        BUILTIN_DECLS,
        FORBIDDEN,
        evaluatePawnNumericExpr,
        getCtrlCharStateForContent
    } = sharedRuntime;

    const {
        hoverFeature,
        resolvePersistentHoverTarget,
        buildHoverAtPosition
    } = createHoverRuntimeFeature({
        vscode,
        refreshExtensionSettings,
        affectsAnyConfiguration,
        HOVER_RELEVANT_CONFIG_KEYS,
        getHoverMode,
        getHoverContentMode,
        getIncludeValidationMode,
        hoverOutputChannel: liveValidationOutputChannel,
        getLiveValidationIssueMode,
        normalizeLiveValidationIssueMode,
        areLiveValidationWarningsEnabled,
        isHoverGoToDefinitionLinksEnabled,
        getIncludeFileExtensions,
        getGlobalIncludePaths,
        getProjectLocalIncludePaths,
        getProgrammaticIncludePaths,
        t,
        buildCommandLink: support.buildCommandLink,
        getWordAtPosition,
        computeLineDepths,
        findPreferredKnownCallContext,
        findNestedParentCallNameContext,
        findFunctionDeclarationNameContext,
        findDefinitionContext,
        hasIncludeFunctionTwin,
        isKnownFunctionName,
        isNearbyCallContext,
        isMeaningfulCallCursorPosition,
        findIndexedAccessContextAtPosition,
        buildIndexedAccessSelectionModel,
        resolveDefaultAccessSymbolName,
        evaluatePawnNumericExpr,
        FORBIDDEN,
        getActiveCtrlChar,
        stripLineComment,
        isEscapedQuote,
        getDocumentTextAndResolver,
        collectWordDeclMatches,
        BUILTIN_DECLS,
        getDeclMatchKey,
        parseDimsParts,
        extractEnumSymbolName,
        buildSig,
        splitTopLevel,
        splitTopLevelWithRanges,
        buildCallArgLayout,
        collectCallArgumentIssues,
        expandObjectLikeDefineTupleCallArgs,
        createLazyCallContextOptions,
        createHoverTypeAnalysisCache,
        resolveIndexedAccessValidationChain,
        parseIndexedAccessExpression,
        explainIndexedAccessDimCompat,
        isFunctionLikeDefineDecl,
        isSameFilePath,
        isFunctionLikeDecl,
        buildEnumMemberLine,
        getVariableInitializerUsageText,
        getEnumDeclsForVariableDims,
        parseDimSpec,
        measurePawnStringLiteral,
        getPawnDocumentContext,
        getLookupTokenAtPosition,
        isLinePositionInsideCommentOrString,
        collectIndexedAccessExpressionsFromLine,
        getCtrlCharStateForContent,
        findVariableDeclarationSpanInRange,
        shouldSuppressVariableDeclarationValidationInRange,
        isVariableDeclarationNameAtPosition,
        findHeaderFunctionByNameAtPosition,
        isOriginalDeclarationHover,
        findFunctionCallNameContext,
        findCallContext,
        findMatchingParenOffset,
        collectInlineNamedCallContexts,
        getPreferredFunctionHoverMatch,
        parseFuncArgs,
        finalizeDeclMatches,
        extractCallSiteArgs,
        isMeaningfulCallPosition
    });

    const persistentHoverFeature = createPersistentHoverFeature({
        vscode,
        isPawnDocument,
        getPawnDocumentContext,
        resolvePersistentHoverTarget,
        getPersistentHoverMode,
        isPersistentHoverEnabled,
        getHoverMode,
        affectsAnyConfiguration,
        PERSISTENT_HOVER_RELEVANT_CONFIG_KEYS,
        computeFunctionRangeMaps
    });

    return {
        persistentHoverFeature,
        hoverFeature,
        buildHoverAtPosition
    };
}

module.exports = { buildHoverFeatures };
