const {
    createDocumentContextCore
} = require('../../core/document-context/runtime');
const {
    createDocumentIncludeSystem
} = require('../../core/document-context/pawn-includes');
const { createCacheMaintenanceService } = require('../../services/cache-maintenance');

function createDocumentSystemRuntime(deps) {
    const {
        vscode,
        fs,
        path,
        context,
        isPawnDocument,
        normalizeFsPath,
        getGlobalIncludePaths,
        getProjectLocalIncludePaths,
        getProgrammaticIncludePaths,
        getIncludeFileExtensions,
        getIncludeDocumentWarmupFileLimit,
        getPersistentIncludeDeclarationCacheMaxBytes,
        resolvedIncludePathCache,
        searchPathCache,
        projectIncludeSourceCache,
        preprocessPawnContent,
        withCtrlCharForContent,
        stripLineComment,
        stripCommentsFromLines,
        getIncludeNameFromLine,
        getIncludePreprocessedStateKey,
        getIncludeDeclCacheKey,
        getActiveIncludeDeclsCacheKey,
        getDefineStateKey,
        includeFileDecls,
        getFileStamp,
        readNormalizedFileContent,
        isSameFileStamp,
        getFileSnapshot,
        getCtrlCharStateForContent,
        computeLineDepths,
        extractDocs,
        parseEnumBlock,
        getPotentialDeclarationStartLineKind,
        collectDeclarationText,
        collectDefineDeclarationText,
        parseDeclLine,
        parsePreprocessorSingleIdentifierPayload,
        activeIncludeDeclsCache,
        areDependencyStampsFresh,
        buildDependencyStampMap,
        normalizeExtensionList,
        createCtrlCharResolver,
        parseFileDecls,
        filterEnumEvalOuterDecls,
        buildDocumentDeclLookup,
        getDocumentContextCacheKey,
        getSharedDocumentContextCacheKey,
        sharedDocumentContextCache,
        documentContextVersionHistory,
        documentEditImpactHistory,
        documentContextCache,
        trackVersionedDocumentCacheVersion,
        touchDocumentContextCacheFile,
        pruneDocumentContextCache,
        documentWarmupTimers,
        touchWarmedIncludeDocument,
        includeFileTextCache,
        fileSnapshotCache,
        commentAnalysisCache,
        ctrlCharStateCache,
        fileDeclParseCache,
        documentContextFileLru,
        funcArgsParseCache,
        liveValidationFullResultCache,
        includeDocumentModelWarmCache,
        bumpDependencyFreshnessVersion,
        invalidateFileStamp,
        clearFileDeclParseCacheForFile,
        clearActiveIncludeDeclsCacheForFile,
        clearDocumentContextCacheForFile,
        clearIncludeDeclCacheForFile,
        clearIncludeFileTextCacheForFile,
        clearFileSnapshotCacheForFile,
        parsePreprocessorDirectiveLine,
        isExplicitDeclarationStartLine,
        liveValidationOutputChannel = null
    } = deps;

    const includeSystemRuntime = createDocumentIncludeSystem({
        vscode,
        fs,
        path,
        getGlobalIncludePaths,
        getProjectLocalIncludePaths,
        getProgrammaticIncludePaths,
        getIncludeFileExtensions,
        normalizeFsPath,
        resolvedIncludePathCache,
        searchPathCache,
        projectIncludeSourceCache,
        preprocessPawnContent,
        withCtrlCharForContent,
        stripLineComment,
        stripCommentsFromLines,
        getIncludeNameFromLine,
        getIncludePreprocessedStateKey,
        getIncludeDeclCacheKey,
        getActiveIncludeDeclsCacheKey,
        getDefineStateKey,
        includeFileDecls,
        getFileStamp,
        readNormalizedFileContent,
        isSameFileStamp,
        getFileSnapshot,
        getCtrlCharStateForContent,
        computeLineDepths,
        extractDocs,
        parseEnumBlock,
        getPotentialDeclarationStartLineKind,
        collectDeclarationText,
        collectDefineDeclarationText,
        parseDeclLine,
        parsePreprocessorDirectiveLine,
        parsePreprocessorSingleIdentifierPayload,
        activeIncludeDeclsCache,
        areDependencyStampsFresh,
        buildDependencyStampMap,
        normalizeExtensionList,
        persistentIncludeDeclCacheRoot: context?.globalStorageUri?.fsPath || '',
        persistentIncludeDeclCacheMaxBytes: () => typeof getPersistentIncludeDeclarationCacheMaxBytes === 'function'
            ? getPersistentIncludeDeclarationCacheMaxBytes()
            : 24 * 1024 * 1024
    });

    const documentContextRuntime = createDocumentContextCore({
        vscode,
        isPawnDocument,
        normalizeFsPath,
        getIncludeDocumentWarmupFileLimit,
        getSearchPaths: includeSystemRuntime.getSearchPaths,
        getCtrlCharStateForContent,
        withCtrlCharForContent,
        preprocessPawnContent,
        getFileSnapshot,
        getActiveDecls: includeSystemRuntime.getActiveDecls,
        createCtrlCharResolver,
        parseFileDecls,
        filterEnumEvalOuterDecls,
        buildDocumentDeclLookup,
        getDocumentContextCacheKey,
        getSharedDocumentContextCacheKey,
        sharedDocumentContextCache,
        documentContextVersionHistory,
        documentEditImpactHistory,
        documentContextCache,
        trackVersionedDocumentCacheVersion,
        touchDocumentContextCacheFile,
        pruneDocumentContextCache,
        buildDependencyStampMap,
        areDependencyStampsFresh,
        documentWarmupTimers,
        touchWarmedIncludeDocument,
        debugOutputChannel: liveValidationOutputChannel
    });

    const cacheRuntime = createCacheMaintenanceService({
        vscode,
        isPawnDocument,
        normalizeFsPath,
        includeFileDecls,
        includeFileTextCache,
        fileSnapshotCache,
        commentAnalysisCache,
        ctrlCharStateCache,
        resolvedIncludePathCache,
        searchPathCache,
        projectIncludeSourceCache,
        fileDeclParseCache,
        activeIncludeDeclsCache,
        sharedDocumentContextCache,
        documentContextCache,
        documentEditImpactHistory,
        documentContextFileLru,
        funcArgsParseCache,
        liveValidationFullResultCache,
        includeDocumentModelWarmCache,
        documentWarmupTimers,
        bumpDependencyFreshnessVersion,
        invalidateFileStamp,
        clearFileDeclParseCacheForFile,
        clearActiveIncludeDeclsCacheForFile,
        clearDocumentContextCacheForFile,
        clearIncludeDeclCacheForFile,
        clearIncludeFileTextCacheForFile,
        clearFileSnapshotCacheForFile,
        clearIncludeCompletionSourceCache: includeSystemRuntime.clearIncludeCompletionSourceCache,
        clearScheduledWarmup: documentContextRuntime.clearScheduledWarmup,
        parsePreprocessorDirectiveLine,
        isExplicitDeclarationStartLine,
        warmDocumentContext: documentContextRuntime.warmDocumentContext,
        warmIncludedDocumentModels: documentContextRuntime.warmIncludedDocumentModels
    });

    return {
        getFileSnapshot,
        ...includeSystemRuntime,
        ...documentContextRuntime,
        ...cacheRuntime
    };
}

module.exports = { createDocumentSystemRuntime };
